# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "cs-ls-ps-env0-state"
    dynamodb_table = "cs-ls-ps-env0-state"
    encrypt        = true
    key            = "env/next/azure/eastus/kubernetes/platform/terraform.tfstate"
    region         = "us-east-1"
  }
}
