apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: azure-disk-csi-driver
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/kubernetes-sigs/azuredisk-csi-driver.git
  ref:
    tag: v1.31.0
