apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-storage-classes
  namespace: region-flux-releases
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: azure-storage-classes
      #version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: flux-system
      interval: 5m
  releaseName: azure-storage-classes
  targetNamespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
  dependsOn:
    - name: azure-disk
    - name: azure-file
  values:
    resources:
      - apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: managed-premium
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
        provisioner: disk.csi.azure.com
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        volumeBindingMode: WaitForFirstConsumer
        parameters:
          skuName: Premium_LRS
          cachingmode: ReadOnly
          kind: managed-premium
