apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: application-gateway-ingress-controller
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: application-gateway-kubernetes-ingress
      version: "1.7.1"
      sourceRef:
        kind: HelmRepository
        name: application-gateway-ingress
        namespace: flux-system
  releaseName: application-gateway-ingress-controller
  values:
    appgw:
      subscriptionID: "${subscription_id}"
      resourceGroup: "${resource_group_name}"
      name: "${application_gateway_name}"
    armAuth:
      type: aadPodIdentity
    aadPodIdentity:
      enabled: true
    verbosityLevel: 3
    watchNamespace: ""
    enableSslCertificateController: true  
