apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: region-flux-releases
spec:
  acme:
    email: ${email}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      -dns01:
        azureDNS:
          subscriptionID: "{azure_subscription_id}"
          resourceGroupName: "${azure_dns_resource_group}"
          hostedZoneName: "${azure_dns_zone_name}"
          managedIdentity:
            clientID: "${azure_ad_app_id}"