apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: aws-ebs
  namespace: region-flux-releases
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: "aws-ebs-csi-driver"
      version: "2.29.1"
      sourceRef:
        kind: HelmRepository
        name: aws-ebs
        namespace: flux-system
      interval: 5m
  releaseName: aws-ebs
  targetNamespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    controller:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: ${iam_role_arn}

      # Specifies whether Leader Election resources should be created
      # Required when running as a Deployment
      # NOTE: Leader election can't be activated if DryRun enabled
      resources:
        requests:
          cpu: 500m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 512Mi
      priorityClassName: "system-cluster-critical"

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ebs-csi-controller
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      topologySpreadConstraints:
        - maxSkew: 2
          minDomains: 2
          whenUnsatisfiable: DoNotSchedule
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchLabels:
              app: ebs-csi-controller
          matchLabelKeys:
            - pod-template-hash
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: ebs.csi.aws.com/agent-not-ready
          operator: Exists
        - key: efs.csi.aws.com/agent-not-ready
          operator: Exists
    node:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: ebs.csi.aws.com/agent-not-ready
          operator: Exists
        - key: efs.csi.aws.com/agent-not-ready
          operator: Exists
