apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: karpenter-node-pools
  namespace: region-flux-releases
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: raw
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: flux-system
      interval: 5m
  releaseName: karpenter-node-pools
  targetNamespace: karpenter
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: warn
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  dependsOn:
    - name: karpenter-node-classes
  values:
    templates:
      - |
        apiVersion: karpenter.sh/v1beta1
        kind: NodePool
        metadata:
          name: general
        spec:
          template:
            metadata:
              # Labels are arbitrary key-values that are applied to all nodes
              labels:
                storageClass: "network"
            spec:
              nodeClassRef:
                name: al2-v4
              requirements:
                - key: "kubernetes.io/os"
                  operator: In
                  values: ["linux"]
                - key: "karpenter.k8s.aws/instance-encryption-in-transit-supported"
                  operator: In
                  values: ["true"]
                - key: "karpenter.k8s.aws/instance-hypervisor"
                  operator: In
                  values: ["nitro"]
                - key: "karpenter.k8s.aws/instance-local-nvme"
                  operator: DoesNotExist
                - key: "karpenter.k8s.aws/instance-category"
                  operator: In
                  values: ["c", "m", "r"]
              startupTaints:
                - key: node.cilium.io/agent-not-ready
                  value: "true"
                  effect: NoExecute
                - key: ebs.csi.aws.com/agent-not-ready
                  value: "true"
                  effect: NoExecute
                - key: efs.csi.aws.com/agent-not-ready
                  value: "true"
                  effect: NoExecute
              kubelet:
                podsPerCore: 20
                maxPods: 100
          limits:
            cpu: 1000
          disruption:
            consolidationPolicy: WhenUnderutilized
          weight: 100
      - |
        apiVersion: karpenter.sh/v1beta1
        kind: NodePool
        metadata:
          name: storage
        spec:
          template:
            spec:
              nodeClassRef:
                name: al2-storage-v4
              requirements:
                - key: "kubernetes.io/arch"
                  operator: In
                  values: ["amd64"]
                - key: "kubernetes.io/os"
                  operator: In
                  values: ["linux"]
                - key: "karpenter.k8s.aws/instance-encryption-in-transit-supported"
                  operator: In
                  values: ["true"]
                - key: "karpenter.k8s.aws/instance-generation"
                  operator: Gt
                  values: ["3"]
                - key: "karpenter.k8s.aws/instance-hypervisor"
                  operator: In
                  values: ["nitro"]
                - key: "karpenter.k8s.aws/instance-category"
                  operator: In
                  values: ["i"]
                - key: "karpenter.k8s.aws/instance-cpu"
                  operator: Gt
                  values: ["4"]
                - key: "karpenter.k8s.aws/instance-local-nvme"
                  operator: Exists
              startupTaints:
                - key: node.cilium.io/agent-not-ready
                  value: "true"
                  effect: NoExecute
                - key: ebs.csi.aws.com/agent-not-ready
                  value: "true"
                  effect: NoExecute
                - key: efs.csi.aws.com/agent-not-ready
                  value: "true"
                  effect: NoExecute
              # taints:
              #   - key: topolvm.io/local
              #     value: "true"
              #     effect: PreferNoSchedule
              kubelet:
                podsPerCore: 20
                maxPods: 100
          limits:
            cpu: 1000
          disruption:
            consolidationPolicy: WhenUnderutilized
          weight: 20
