apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: region-flux-releases
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.7.2"
      sourceRef:
        kind: HelmRepository
        name: aws-eks
        namespace: flux-system
      interval: 5m
  releaseName: aws-load-balancer-controller
  targetNamespace: kube-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment

  values:
    enableCertManager: true
    replicas: 2

    defaultTargetType: ip
    ingressClass: null
    createIngressClassResource: false
    clusterName: ${cluster_name}
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${iam_role_arn}
    controller:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 256Mi
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - aws-load-balancer-controller
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - aws-load-balancer-controller
            topologyKey: kubernetes.io/hostname
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux

    topologySpreadConstraints:
      - maxSkew: 2
        minDomains: 2
        whenUnsatisfiable: DoNotSchedule
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: aws-load-balancer-controller
            app.kubernetes.io/instance: aws-load-balancer-controller
        matchLabelKeys:
          - pod-template-hash
    priorityClassName: "system-cluster-critical"
